# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10-GDlIOim-b8WAnnhmno-e2d5CGsrMW6
"""

numero1 = input("Digite o número 1: ")

print(numero1)

operacao = input("Digite uma das quatro operações: +, -, /, *  :")

print(operacao)

numero2 = input("Digite o número 2: ")

print(numero2)

numero1 = float(numero1)
numero2 = float(numero2)

if operacao == "+":
  resultado = numero1 + numero2

if operacao == "-":
  resultado = numero1 - numero2

if operacao == "*":
  resultado = numero1 * numero2

if (operacao == "/"):
  resultado = numero1 / numero2

print (resultado)